---
title: "Building a {distil} website"
description: |
  How did I build this website? 
author:
  - name: Orkhan Sariyev
date: 2023-08-10
preview: preview_post1.jpg
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In my inaugural blog post, I am excited to share a comprehensive list of resources that proved instrumental in the construction of this website. For those who may be newcomers to the realms of both `R markdown` and `distil`, I trust that this post will serve as a valuable aid. While I myself am relatively new to these tools, I have grown more at ease with markdown through various projects. A fortunate advantage is the wealth of individuals who have generously shared their insights and are enthusiastic about guiding fellow learners like us.

My initiation into the world of distil occurred through a mention on Twitter. How do you usually respond to news of something new? Researching on Google or exploring YouTube videos perhaps? I embarked on a similar journey! Eventually, I stumbled upon [Lisa Lendway's](https://lisalendway.netlify.app/) website which, by the way, she constructed using `distil`. Furthermore, there is also a [Youtube video](https://www.youtube.com/watch?time_continue=186&v=Fm3bsYCilEU&embeds_referring_euri=https%3A%2F%2Flisalendway.netlify.app%2F&source_ve_path=MjM4NTE&feature=emb_title). This was already good enough to set up my webpage over night!

My subsequent step involved exploring various [example websites](https://pkgs.rstudio.com/distill/articles/examples.html) as provided by the `distil` documentation. . I am sure by googling a bit more, one can find many other example websites built with `distil` that provide code publicly. One of these sources is definitely [Open Source Football](https://github.com/nflverse/open-source-football).

I soon realized I had forgotten to add my email to the website. I wanted to have it on the main page as a footer, and realized [Open Source Football](https://github.com/nflverse/open-source-football) had a footer too! Checking their `GitHub`, I realized they had a _footer.html file which must be what I need. Again, with some googling I found out about [rstudio4edu](https://rstudio4edu.github.io/rstudio4edu-book/) which has a lot of information on markdown, distill, and bookdown. Next step was to make the footer look nice! I searched for HTML email tag and envelope icon, and added them into the html (actually a text) file; and boom! Very easy!   

I am still constructing my website, thus this blog will be updated constantly. 


